[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/components/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
